baseURL: "https://tiagodread.github.io/"
title: Quality Engineering Logbook
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: "G-ERLFKFV0DG"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Quality Engineering Logbook
  description: ""
  keywords: [Blog, Portfolio, QA]
  author: by Tiago Góes
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Quality Engineering Logbook"
    icon: /apple-touch-icon.png
    iconHeight: 35

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: |
      I'm Tiago, Software Quality Engineer and this is my personal blog site
      >
      - 🌱  I'm current learning more about Blockchain, De-Fi, DApps and more! 
      >
      - 💬 Ask me about Agile Testing (Web/Mobile/API), Agile Methodologies, Cypress, Selenium, Appium, Maestro, Robotframework, WebdriverIO, Applitools, Browserstack, etc.
      >
      You can also find me on:

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/tiagogs/"
    - name: twitter
      url: "https://twitter.com/tiagogoes_"
    - name: email
      url: "mailto:tiago.goes2009@gmail.com"
    - name: github
      url: "https://github.com/tiagodread"

  analytics:
    google:
      SiteVerificationTag: "G-ERLFKFV0DG"

  cover:
    image: "https://avatars.githubusercontent.com/u/12464858?s=400&u=6676e7e659439de64686c110be5323d9cc55ee04&v=4"
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

publishDir: "docs"
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  pt:
    contentDir: content/pt
    disabled: false
    languageCode: pt-br
    languageDirection: ltr
    languageName: Portuguese
    params:
      subtitle: Postagens sobre qualidade de software
    title: Quality Engineering Logbook
    weight: 2
    menu:
      main:
        - identifier: home
          name: Inicio
          url: /
          weight: 5
        - identifier: about
          name: Sobre
          url: /sobre/
          weight: 10
        - identifier: archives
          name: Arquivos
          url: /arquivos/
          weight: 30
        - identifier: categories
          name: Categorias
          url: /categories/
          weight: 40
        - identifier: search
          name: Busca
          url: /busca/
          weight: 60
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Posts about software quality
    title: Quality Engineering Logbook
    weight: 1
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 5
        - identifier: about
          name: About
          url: /about/
          weight: 10
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 30
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 40
        - identifier: search
          name: Search
          url: /search/
          weight: 60
